### ISSUE TITLE
Parser recovers on syntax errors rather than exiting with an error.

### ISSUE THREAD

**Issue by mutcianm** [mutcianm/lolcodec#1]
This issue should be resolved by subclassing lolcodeParser and overriding some methods responsible for parse error handling.

**Comment by vmironovich** [comment]
"This issue should be resolved by subclassing lolcodeParser and overriding some methods responsible for parse error handling."

Gotta read section 9 in TDAntlr4Reference, especially 9.5, it is supposed to provide right solution, IMO.

http://media.pragprog.com/titles/tpantlr2/code/errors/BailErrorStrategy.java
http://media.pragprog.com/titles/tpantlr2/code/errors/TestBail.java

**Comment by vmironovich** [comment]
https://github.com/dedoz/lolcodellvm/commit/3dab0959a6f95aaf5ab143372974b565a739357e
