### ISSUE TITLE
com.lolcode.tree.TreeFuncCallStmt cannot be cast to com.lolcode.tree.TreeExpression

### ISSUE THREAD

**Issue by vmironovich** [mutcianm/lolcodec#10]
when calling function within function call, see https://github.com/dedoz/lolcodellvm/commit/07f189a4056629cf6ba55d8ac4f81a6584b4bc15

**Comment by mutcianm** [comment]
So, the solution is pretty radical.
- introduce new statement that can hold an expression
- make function call an expression(why the hell was it a statement anyway?)
- this by the way allows to write things like SUM OF 123 AN 321 straight away without any decorators
