### ISSUE TITLE
TreeFunctionParameter not working.

### ISSUE THREAD

**Issue by vmironovich** [mutcianm/lolcodec#5]
com.lolcode.tree.TreeConstant cannot be cast to com.lolcode.tree.TreeFunctionParameter
testfunc 2 BTW function call with constant

com.lolcode.tree.TreeVariable cannot be cast to com.lolcode.tree.TreeFunctionParameter
testfunc VAR BTW function call with variable

https://github.com/dedoz/lolcodellvm/commit/0995906dcf6ab5f9ddaef23f401e33facb89ca22

**Comment by mutcianm** [comment]
closed again in
