### ISSUE TITLE
BOOL values are treated like IDs rather than values

### ISSUE THREAD

**Issue by mutcianm** [mutcianm/lolcodec#6]
Files get parsed incorrectly: parser takes TROOF values for IDs. 

ATSBuilder then generates TreeVariable nodes with "WIN" or "FAIL" names instead of BOOL-typed TreeConstant nodes.
If you debug ASTBuilder you should see that visitExpr() gets calles instead of visitValue().

**Comment by vmironovich** [comment]
Proposed fix (seems working) : 
value
    :   INT 
    |   STRING
    |   FLOAT
    |   BOOL
    ;

INT : ('-')?[0-9]+  ;

STRING : '"' [\u0000-\u0021\u0023-\uFFFE]\* '"';

FLOAT : (-)? [0-9]? '.' [0-9]+ ('f'|'F')? ;

BOOL : 'WIN' | 'FAIL' ;

ID : LETTER ( LETTER | [0-9_] )*;
fragment
LETTER : [a-zA-Z] ;

as in "Move ID rule after value rules and subrules", also I thing we'd better use 'fragment' keyword in INT-STRING-FLOAT and so on, but I didn't look into it that much at the time of grammar writing.
