### ISSUE TITLE
function call statements parsed incorrectly

### ISSUE THREAD

**Issue by mutcianm** [mutcianm/lolcodec#8]
Variables in function calls are treated as function calls rather than expressions.
For example:

```
HOW DUZ I TESTFUNC... - function taking 3 arguments
gets called like this:
TESTFUNC "somevalue" VAR1 123
```

"VAR1 123" part gets parsed as a call of function named VAR1 with argument 123.
Current grammar implementation does not provide a clear way to distinguish between a function call with list of arguments and the list of arguments itself.
A solution might be to explicitly mark values passed as arguments list just like in function declaration statement, for example:

```
TESTFUNC YR "somevalue" N YR VAR1 N YR 123
```

**Comment by mutcianm** [comment]
btw, I'm currently not bored enough to read whatever official standard has to say about this problem
and i've lost the link, again

**Comment by vmironovich** [comment]
Pseudo working, https://github.com/dedoz/lolcodellvm/commit/07f189a4056629cf6ba55d8ac4f81a6584b4bc15 maybe will be fixed more.
